
angular
  .module('classroom')
  .constant('LANG_EN', {

    all: 'All',
    available_courses: 'Available Courses',
    by_name: 'By name',
    by_progress: 'By progress',
    comment: 'Comment',
    comment_solution: 'Comment',
    comment_this_solution: 'Comment this solution',
    complete_form: 'Complete form',
    copied: 'Copied',
    day_friday: 'Friday',
    day_monday: 'Monday',
    day_saturday: 'Saturday',
    day_sunday: 'Sunday',
    day_thursday: 'Thursday',
    day_tuesday: 'Tuesday',
    day_wednesday: 'Wednesday',
    email_not_provided: 'Email not provided',
    expectations: 'Expectations',
    filter_available_courses: 'Filter available courses',
    filter_available_guides: 'Filter available guides',
    filter_students: 'Filter students',
    first_name: 'First name',
    first_name_error: 'First name is mandatory',
    follow: 'Follow',
    guides: 'Guides',
    hide_details: 'Hide details',
    last_name: 'Last name',
    last_name_error: 'Last name is mandatory',
    log_in: 'Log in',
    log_in_first: 'You must login first',
    log_out: 'Log out',
    my_courses: 'My courses',
    new_course: 'New course',
    new_course_code: 'Course code',
    new_course_code_error: 'Course code is mandatory',
    new_course_days_error: 'Select at least one day',
    new_course_description: 'Course description',
    new_course_description_error: 'Description is mandatory',
    new_course_name: 'Course name',
    new_course_name_error: 'Course name can only contain letters, numbers, dashes or underscores',
    new_course_period: 'Period - i.e. 2000 or 2001-1S',
    new_course_period_error: 'Period invalid format',
    new_course_shift: 'Shift',
    new_course_shift_error: 'Select at least one shift',
    no_courses_to_show: 'There is no courses to show',
    no_guides_to_show: 'There is no guides to show',
    no_students_to_show: 'There is no students to show',
    only_followers: 'Only following',
    open_in_atheneum: 'Open in Atheneum',
    results: 'Results',
    shift: 'Shift',
    shift_afternoon: 'Afternoon',
    shift_morning: 'Morning',
    shift_night: 'Night',
    show_details: 'Show details',
    students: 'Students',
    students_subscription_address: 'Students subscription address',
    submit: 'Submit',
    submitted_solutions: 'Submitted solutions',
    tests: 'Tests',
    unfollow: 'Unfollow'

  });
