
angular
  .module('classroom')
  .constant('LANG_PT', {

    add_multiple_students: 'Adicione vários alunos',
    add_permissions_to_teacher: 'Adicionar permissões para',
    added_teacher: 'Professor adicionado',
    all: 'Todos',
    are_you_sure_attach_student_from_course: 'Tem certeza de que deseja colocar o aluno no curso?',
    are_you_sure_delete_student_from_course: 'Tem certeza de que deseja remover o aluno do curso?',
    are_you_sure_detach_student_from_course: 'Tem certeza de que deseja separar o aluno do curso?',
    attach: 'Anexar',
    available_courses: 'Cursos disponíveis',
    bulk: 'Massa',
    by_last_submission_date: 'Na última data de apresentação',
    by_messages: 'Por contagem de mensagens pendentes',
    by_name: 'Pelo nome',
    by_progress: 'Pelo progresso',
    by_signup_date: 'Por data de inscrição',
    cancel: 'Cancelar',
    comment_solution: 'Comente',
    comment_this_solution: 'Comente esta solução',
    comment: 'Comente',
    complement: 'Complemento',
    complements: 'Complementos',
    complete_form: 'Preencha sua informação',
    confirm: 'confirme',
    copied: 'Copiado',
    correct_permissions: 'Permissões concedidas corretamente',
    course: 'Curso',
    courses: 'Cursos',
    date_format: 'MM/dd / aaaa',
    day_friday: 'Sexta-feira',
    day_monday: 'Segunda-feira',
    day_saturday: 'sábado',
    day_sunday: 'domingo',
    day_thursday: 'Quinta-feira',
    day_tuesday: 'terça',
    day_wednesday: 'Quarta-feira',
    detach_students: 'Estudantes separados',
    detach: 'Desanexar',
    diff: 'Diff',
    do_comment: 'Comentário bem sucedido!',
    do_follow: 'Segue!',
    duration_placeholder: 'Minutos',
    duration: 'Duração',
    edit: 'Editar',
    edit_exam: 'Editar exame',
    edit_student: 'Editar estudante',
    email_error: 'O e-mail é obrigatório e deve ser válido',
    email_not_provided: 'E-mail não fornecido',
    email: 'O email',
    empty_notifications: 'Não há notificações para mostrar',
    end_time: 'Fim do tempo',
    evaluate: 'Avalie',
    exam_link: 'Link de exame',
    exam_updated: 'Exame atualizado com sucesso',
    exam: 'Exame',
    exams: 'Exames',
    example: 'Exemplo',
    example_csv_link: 'Faça o download de um exemplo CSV clicando <a href="/assets/csv/example.pt.csv" download="exemplo.csv" target="_blank">aqui</a>',
    example_csv_title: 'Você também pode enviar vários alunos carregando um arquivo CSV',
    exercise_status_default: 'Pendente',
    exercise_status_errored: 'Oops, sua solução não funcionou',
    exercise_status_failed: 'Opa, algo deu errado',
    exercise_status_passed: 'Tudo bem',
    exercise_status_passed_with_warnings: 'Funcionou, mas você pode fazer melhor',
    exercise: 'Exercício',
    expectations: 'Expectativas',
    export_course_report: 'Gerar relatório de curso',
    export_guide_report: 'Gerar relatório de guia',
    export_solutions_button: 'Soluções de exportação',
    export_solutions_disclaimer: 'Atenção! Estes dados são sensíveis. Não use ou distribua-lo sem o consentimento explícito dos usuários. <br> <br> Você quer continuar de qualquer maneira?',
    export_solutions_title: 'Exporte soluções de {{courseName}}',
    failed: 'Falhou',
    filter_available_courses: 'Filtre os cursos disponíveis',
    filter_available_exams: 'Filtre os exames disponíveis',
    filter_available_guides: 'Filtrar guias disponíveis',
    filter_passed_assignments: 'Filtrar por exercícios aprovados',
    filter_students: 'Filtre os alunos',
    filter_teachers: 'Filtrar professores',
    first_name_error: 'O nome é obrigatório',
    first_name: 'Primeiro nome',
    follow: 'Segue',
    guide: 'Guia',
    guides: 'Guias',
    hide: 'ocultar',
    invitation_link: 'Curso junte-se a nós',
    invite_students: 'Convide estudantes',
    last_lesson: 'Última lição',
    last_name_error: 'O sobrenome é obrigatório',
    last_name: 'Último nome',
    last_solution: 'Última solução',
    lesson: 'Lição',
    log_in_first: 'Você deve fazer login primeiro',
    log_in: 'Entrar',
    log_out: 'Sair',
    manual_evaluation: 'Avaliação manual',
    mark_as_read: 'marcar como Lido',
    mark_as_unread: 'marcar como não lido',
    max_problem_submissions: 'Limite de envio para problemas',
    max_choice_submissions: 'Limite de envio para teóricos',
    message: 'Mensagem de {{sender}}',
    messages: 'Mensagens',
    more_messages: 'Carregue mais',
    more_notifications: 'Ver todas as notificações',
    new_course_code_error: 'O código do curso é obrigatório',
    new_course_code: 'Código do curso - ou seja, K2000 ou ABC-123',
    new_course_days_error: 'Selecione pelo menos um dia',
    new_course_description_error: 'Descrição obrigatória',
    new_course_description: 'Descrição do Curso',
    new_course_name_error: 'O nome do curso só pode conter letras, números, traços ou sublinhados',
    new_course_name: 'Nome do curso',
    new_course_period_error: 'Formato inválido do período',
    new_course_period: 'Período - ou seja, 2000 ou 2001-1S',
    new_course_shift_error: 'Selecione pelo menos um turno',
    new_course_shift: 'Mudança',
    new_course: 'Novo curso',
    new_exam: 'Novo exame',
    new_message: 'Nova mensagem',
    new_student: 'Novo estudante',
    new_teacher: 'Novo professor',
    next_exercise_description: 'Vá para o próximo exercício',
    next_solution_description: 'Vá para a próxima solução',
    no_courses_to_show: 'Não há cursos para mostrar',
    no_exams_to_show: 'Não há exames para mostrar',
    no_guides_to_show: 'Não há guias para mostrar',
    no_solutions_sent: 'Nenhuma solução enviada',
    no_students_to_show: 'Não há estudantes a mostrar',
    no: 'Não',
    notifications: 'Notificações',
    only_followers: 'Apenas seguindo',
    others: 'Outras',
    passed: 'Passado',
    personal_id: 'Identificação pessoal',
    personal_id_placeholder: 'Identificação Pessoal (opcional)',
    prev_exercise_description: 'Vá para o exercício anterior',
    prev_solution_description: 'Vá para a solução anterior',
    registered: 'Registrado',
    remove: 'Remover',
    results: 'Resultados',
    save: 'Salve',
    send: 'Enviar',
    shift_afternoon: 'Tarde',
    shift_morning: 'Manhã',
    shift_night: 'Noite',
    shift: 'Mudança',
    show_students: 'Mostrar estudantes',
    show: 'exposição',
    sign_up: 'inscrever-se',
    single: 'solteiro',
    singup_date: 'Data de inscrição',
    solution_sent_at_format: 'MMMM DD AAAA - h: mm a',
    solved_at: 'Resolvido {{date}}',
    split: 'Dividido',
    start_time: 'Hora de início',
    students_subscription_address: 'Endereço de inscrição dos estudantes',
    students: 'Estudantes',
    submissions_count: '{{submissionsCount}} soluções enviadas. Última solução: {{lastSubmissionDate}}',
    submit: 'Enviar',
    suggestions: 'Últimas mensagens enviadas para este exercício:',
    teachers: 'Professores',
    term_and_conditions: 'Concordo com mumuki <a target="_blank" href="{{url}}"> termos e condições. </a>',
    tests: 'Testes',
    total: 'Total',
    transfer: 'Transferir',
    unfollow: 'Deixar de seguir',
    unfollowing: 'Deixar de seguir!',
    unified: 'Unificado',
    upload_file: 'Subir arquivo',
    uploading_file: 'Upload do arquivo',
    view_in_atheneum: 'Vista no Atheneum',
    view_mode: 'Modo de visualização:',
    with_warnings: 'Com advertências',
    yes: 'sim'

  });
