
angular
  .module('classroom')
  .constant('LANG_EN', {

    add_permissions_to_teacher: 'Add permissions to',
    added_teacher: 'Teacher added',
    all: 'All',
    are_you_sure_delete_student_from_course: 'Are you sure you want to remove student from course?',
    available_courses: 'Available Courses',
    by_last_submission_date: 'By last submission date',
    by_name: 'By name',
    by_progress: 'By progress',
    by_signup_date: 'By signup date',
    comment: 'Comment',
    comment_solution: 'Comment',
    comment_this_solution: 'Comment this solution',
    complement: 'Complement',
    complements: 'Complements',
    complete_form: 'Complete form',
    confirm: 'Confirm',
    copied: 'Copied',
    correct_permissions: 'Permissions granted correctly',
    courses: 'Courses',
    date_format: 'MM/dd/yyyy',
    day_friday: 'Friday',
    day_monday: 'Monday',
    day_saturday: 'Saturday',
    day_sunday: 'Sunday',
    day_thursday: 'Thursday',
    day_tuesday: 'Tuesday',
    day_wednesday: 'Wednesday',
    do_comment: 'Successful comment!',
    do_follow: 'Following!',
    duration: 'Duration',
    duration_placeholder: 'Minutes',
    edit_exam: 'Edit exam',
    email: 'Email',
    email_error: 'Email is mandatory and it must be a valid one',
    email_not_provided: 'Email not provided',
    end_time: 'End time',
    exam: 'Exam',
    exam_link: 'Exam link',
    exam_updated: 'Exam updated successfully',
    exams: 'Exams',
    expectations: 'Expectations',
    filter_available_courses: 'Filter available courses',
    filter_available_exams: 'Filter available exams',
    filter_available_guides: 'Filter available guides',
    filter_students: 'Filter students',
    filter_teachers: 'Filter teachers',
    first_name: 'First name',
    first_name_error: 'First name is mandatory',
    follow: 'Follow',
    guide: 'Guide',
    guides: 'Guides',
    hide: 'Hide',
    last_name: 'Last name',
    last_name_error: 'Last name is mandatory',
    last_solution: 'Last solution',
    log_in: 'Log in',
    log_in_first: 'You must login first',
    log_out: 'Log out',
    new_course: 'New course',
    new_course_code: 'Course code - i.e. K2000 or ABC-123',
    new_course_code_error: 'Course code is mandatory',
    new_course_days_error: 'Select at least one day',
    new_course_description: 'Course description',
    new_course_description_error: 'Description is mandatory',
    new_course_name: 'Course name',
    new_course_name_error: 'Course name can only contain letters, numbers, dashes or underscores',
    new_course_period: 'Period - i.e. 2000 or 2001-1S',
    new_course_period_error: 'Period invalid format',
    new_course_shift: 'Shift',
    new_course_shift_error: 'Select at least one shift',
    new_exam: 'New exam',
    new_teacher: 'New teacher',
    no: 'No',
    no_courses_to_show: 'There is no courses to show',
    no_exams_to_show: 'There is no exams to show',
    no_guides_to_show: 'There is no guides to show',
    no_students_to_show: 'There is no students to show',
    only_followers: 'Only following',
    open_in_atheneum: 'Open in Atheneum',
    others: 'Others',
    results: 'Results',
    save: 'Save',
    shift: 'Shift',
    shift_afternoon: 'Afternoon',
    shift_morning: 'Morning',
    shift_night: 'Night',
    show: 'Show',
    show_students: 'Show students',
    singup_date: 'Signup date',
    solution_sent_at_format: 'MMMM DD YYYY - h:mm a',
    solved_at: 'Solved at {{date}}',
    split: 'Split',
    submissions_count: '{{submissionsCount}} solutions sent. Last solution: {{lastSubmissionDate}}',
    start_time: 'Start time',
    students: 'Students',
    students_subscription_address: 'Students subscription address',
    submit: 'Submit',
    teachers: 'Teachers',
    tests: 'Tests',
    unfollow: 'Unfollow',
    unfollowing: 'Unfollow!',
    unified: 'Unified',
    view_mode: 'View Mode: ',
    yes: 'Yes'

  });
