
angular
  .module('classroom')
  .constant('LANG_ES', {

    add_permissions_to_teacher: 'Agregar permisos a',
    all: 'Todos',
    available_courses: 'Cursos disponibles',
    by_name: 'Por nombre',
    by_progress: 'Por progreso',
    comment: 'Comentario',
    comment_solution: 'Comentar',
    comment_this_solution: 'Comentar esta solución',
    complete_form: 'Cargar datos',
    confirm: 'Confirmar',
    copied: 'Copiado',
    courses: 'Cursos',
    day_friday: 'Viernes',
    day_monday: 'Lunes',
    day_saturday: 'Sábado',
    day_sunday: 'Domingo',
    day_thursday: 'Jueves',
    day_tuesday: 'Martes',
    day_wednesday: 'Miércoles',
    do_comment: 'Has comentado correctamente',
    do_follow: 'Siguiendo!',
    email: 'Email',
    email_error: 'El campo email es obligatorio, y debe ser válido',
    email_not_provided: 'No hay email asociado',
    expectations: 'Expectativas',
    filter_available_courses: 'Filtrar cursos disponibles',
    filter_available_guides: 'Filtrar guías disponibles',
    filter_students: 'Filtrar alumnos',
    first_name: 'Nombre',
    first_name_error: 'El campo nombre es obligatorio',
    follow: 'Seguir',
    guides: 'Guías',
    hide_details: 'Ocultar detalles',
    last_name: 'Apellido',
    last_name_error: 'El campo apellido es obligatorio',
    log_in: 'Iniciar sesión',
    log_in_first: 'Tenés que iniciar sesión primero',
    log_out: 'Cerrar sesión',
    new_course: 'Nuevo curso',
    new_course_code: 'Código del curso',
    new_course_code_error: 'El código del curso es obligatorio',
    new_course_days_error: 'Seleccioná al menos un día',
    new_course_description: 'Descripción del curso',
    new_course_description_error: 'El campo descripción es obligatorio',
    new_course_name: 'Nombre del curso',
    new_course_name_error: 'El nombre del curso sólo debe contener letras, números, guiones o guiones bajos',
    new_course_period: 'Período - Ej: 2003 o 2001-2C',
    new_course_period_error: 'Formato del período inválido',
    new_course_shift: 'Turno',
    new_course_shift_error: 'Seleccioná al menos un turno',
    no_courses_to_show: 'No hay cursos para mostrar',
    no_guides_to_show: 'No hay guías para mostrar',
    no_students_to_show: 'No hay alumnos para mostrar',
    only_followers: 'Seguidos',
    open_in_atheneum: 'Abrir en Atheneum',
    results: 'Resultados',
    shift: 'Turno',
    shift_afternoon: 'Tarde',
    shift_morning: 'Mañana',
    shift_night: 'Noche',
    show_details: 'Mostrar detalles',
    solution_sent_at_format: 'DD MMMM YYYY - hh:mm',
    students: 'Alumnos',
    students_subscription_address: 'Dirección de suscripción de alumnos',
    submit: 'Enviar',
    tests: 'Pruebas',
    unfollow: 'Dejar de Seguir',
    unfollowing: 'Has dejado de seguir al usuario',

  });
