
angular
  .module('classroom')
  .constant('LANG_EN', {

    available_courses: 'Available Courses',
    by_name: 'By name',
    by_progress: 'By progress',
    comment: 'Comment',
    comment_solution: 'Comment',
    comment_this_solution: 'Comment this solution',
    complete_form: 'Complete form',
    copied: 'Copied',
    expectations: 'Expectations',
    filter_available_courses: 'Filter available courses',
    filter_available_guides: 'Filter available guides',
    filter_students: 'Filter students',
    first_name: 'First name',
    first_name_error: 'First name is mandatory',
    guides: 'Guides',
    hide_details: 'Hide details',
    last_name: 'Last name',
    last_name_error: 'Last name is mandatory',
    log_in: 'Log in',
    log_in_first: 'You must login first',
    log_out: 'Log out',
    my_courses: 'My courses',
    new_course: 'New course',
    new_course_description: 'Course description',
    new_course_description_error: 'Description is mandatory',
    new_course_name: 'Course name',
    new_course_name_error: 'Course name can only contain letters, numbers, dashes or underscores',
    no_courses_to_show: 'There is no courses to show',
    no_guides_to_show: 'There is no guides to show',
    no_students_to_show: 'There is no students to show',
    open_in_atheneum: 'Open in Atheneum',
    results: 'Results',
    show_details: 'Show details',
    students: 'Students',
    students_subscription_address: 'Students subscription address',
    submit: 'Submit',
    submitted_solutions: 'Submitted solutions',
    tests: 'Tests',

  });
