
angular
  .module('classroom')
  .constant('LANG_ES', {

    add_permissions_to_teacher: 'Agregar permisos a',
    added_teacher: 'Docente agregado satisfactoriamente',
    all: 'Todos',
    attach: 'Vincular',
    are_you_sure_attach_student_from_course: '¿Estás seguro que querés vincular al estudiante al curso?',
    are_you_sure_delete_student_from_course: '¿Estás seguro que querés borrar al estudiante del curso?',
    are_you_sure_detach_student_from_course: '¿Estás seguro que querés desvincular al estudiante del curso?',
    available_courses: 'Cursos disponibles',
    by_last_submission_date: 'Por fecha de ultima solución',
    by_name: 'Por nombre',
    by_progress: 'Por progreso',
    by_signup_date: 'Por fecha de registración',
    cancel: 'Cancelar',
    comment: 'Comentario',
    comment_solution: 'Comentar',
    comment_this_solution: 'Comentar esta solución',
    complement: 'Complemento',
    complements: 'Complementos',
    complete_form: 'Ingresá tus datos',
    confirm: 'Confirmar',
    copied: 'Copiado',
    correct_permissions: 'Permisos otorgados satisfactoriamente',
    courses: 'Cursos',
    date_format: 'dd/MM/yyyy',
    day_friday: 'Viernes',
    day_monday: 'Lunes',
    day_saturday: 'Sábado',
    day_sunday: 'Domingo',
    day_thursday: 'Jueves',
    day_tuesday: 'Martes',
    day_wednesday: 'Miércoles',
    detach: 'Desvincular',
    detach_students: 'Estudiantes desvinculados',
    do_comment: 'Has comentado correctamente',
    do_follow: 'Siguiendo!',
    duration: 'Duración',
    duration_placeholder: 'Minutos',
    edit: 'Editar',
    edit_exam: 'Editar examen',
    email: 'Email',
    email_error: 'El campo email es obligatorio, y debe ser válido',
    email_not_provided: 'No hay email asociado',
    end_time: 'Hasta',
    exam: 'Examen',
    exam_link: 'Link al examen',
    exam_updated: 'Examen guardado satisfactoriamente',
    exams: 'Exámenes',
    expectations: 'Expectativas',
    export_solutions_disclaimer: '¡Cuidado! Estos datos son sensibles. No los utilices ni distribuyas sin el consentimiento de los usuarios.<br><br>¿Deseas continuar de todos modos?',
    export_solutions_button: 'Exportar soluciones',
    export_solutions_title: 'Exportar soluciones de {{courseName}}',
    failed: "Con errores",
    filter_available_courses: 'Filtrar cursos disponibles',
    filter_available_exams: 'Filtrar exámenes disponibles',
    filter_available_guides: 'Filtrar guías disponibles',
    filter_students: 'Filtrar estudiantes',
    filter_teachers: 'Filtrar docentes',
    first_name: 'Nombre',
    first_name_error: 'El campo nombre es obligatorio',
    follow: 'Seguir',
    guide: 'Guía',
    guides: 'Guías',
    hide: 'Ocultar',
    last_lesson: 'Ultima lección',
    last_name: 'Apellido',
    last_name_error: 'El campo apellido es obligatorio',
    last_solution: 'Ultima solución',
    lesson: 'Lección',
    log_in: 'Iniciar sesión',
    log_in_first: 'Tenés que iniciar sesión primero',
    log_out: 'Cerrar sesión',
    new_course: 'Nuevo curso',
    new_course_code: 'Código del curso - Ej: K2000 o ABC-123',
    new_course_code_error: 'El código del curso es obligatorio',
    new_course_days_error: 'Seleccioná al menos un día',
    new_course_description: 'Descripción del curso',
    new_course_description_error: 'El campo descripción es obligatorio',
    new_course_name: 'Nombre del curso',
    new_course_name_error: 'El nombre del curso sólo debe contener letras, números, guiones o guiones bajos',
    new_course_period: 'Período - Ej: 2003 o 2001-2C',
    new_course_period_error: 'Formato del período inválido',
    new_course_shift: 'Turno',
    new_course_shift_error: 'Seleccioná al menos un turno',
    new_exam: 'Nuevo examen',
    new_student: 'Nuevo estudiante',
    new_teacher: 'Nuevo docente',
    next_exercise_description: 'Ir al ejercicio siguiente',
    next_solution_description: 'Ir a la solución siguiente',
    no: 'No',
    no_courses_to_show: 'No hay cursos para mostrar',
    no_exams_to_show: 'No hay exámenes para mostrar',
    no_guides_to_show: 'No hay guías para mostrar',
    no_students_to_show: 'No hay estudiantes para mostrar',
    only_followers: 'Seguidos',
    others: 'Otros',
    passed: 'Correctos',
    prev_exercise_description: 'Ir al ejercicio anterior',
    prev_solution_description: 'Ir a la solución anterior',
    registered: 'Registrado',
    remove: 'Eliminar',
    results: 'Resultados',
    save: 'Guardar',
    shift: 'Turno',
    shift_afternoon: 'Tarde',
    shift_morning: 'Mañana',
    shift_night: 'Noche',
    show: 'Mostrar',
    show_students: 'Ver estudiantes',
    singup_date: 'Registrado',
    sign_up: 'Confirmar',
    solution_sent_at_format: 'DD MMMM YYYY - hh:mm',
    solved_at: 'Resuelto {{date}}',
    split: 'Separado',
    start_time: 'Desde',
    students: 'Estudiantes',
    students_subscription_address: 'Dirección de suscripción de estudiantes',
    submissions_count: '{{submissionsCount}} soluciones enviadas. Última solución: {{lastSubmissionDate}}',
    submit: 'Enviar',
    teachers: 'Docentes',
    term_and_conditions: 'Al registrarte estas aceptando las <a target="_blank" href="{{url}}"> condiciones de uso.</a>',
    tests: 'Pruebas',
    total: 'Total intentados',
    transfer: 'Transferir',
    unfollow: 'Dejar de Seguir',
    unfollowing: 'Has dejado de seguir al usuario',
    unified: 'Unificado',
    view_in_atheneum: 'Ver en Atheneum',
    view_mode: 'Visualización: ',
    with_warnings: 'Con advertencias',
    yes: 'Si'

  });
